# Collabrative Filtering data set taken from Collective Intelligence book.


dataset={
			'Fernanda': {'Beterraba': 2.5,
							'Inhame': 3.5,
							'Couve': 3.0,
							'Tomate': 3.5,
							'Batata': 2.5,
							'Cebola': 3.0},
			'Eduardo': {'Beterraba': 3.0,
							'Inhame': 3.5,
							'Couve': 0,
							 'Tomate': 5.0,
							 'Cebola': 3.0,
							'Batata': 3.5},

			'Caue': {'Beterraba': 2.5,
								'Inhame': 3.0,
								'Tomate': 3.5,
								 'Cebola': 4.0},
			'Pedro': {'Inhame': 3.5,
							'Couve': 3.0,
							'Cebola': 4.5,
							'Tomate': 4.0,
							'Batata': 2.5},
			'Rodrigo': {'Beterraba': 3.0,
							'Inhame': 4.0,
							'Couve': 2.0,
							'Tomate': 3.0,
							'Cebola': 3.0,
							'Batata': 2.0},
			'Bruno': {'Beterraba': 3.0,
							'Inhame': 4.0,
							'Cebola': 3.0,
							'Tomate': 5.0,
							'Batata': 3.5},
			'Carol': {'Inhame':4.5,
					'Batata':1.0,
					'Tomate':4.0}}